"""empty message

Revision ID: 12849a00d90d
Revises: f879646f238a
Create Date: 2025-10-13 15:57:22.283637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12849a00d90d'
down_revision = 'f879646f238a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=15), nullable=False))
        batch_op.drop_constraint(batch_op.f('user_user_key'), type_='unique')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('user_user_key'), ['user'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
