"""empty message

Revision ID: 863eff783e73
Revises: 
Create Date: 2025-12-02 22:01:54.581077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863eff783e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activity_city_id'))
        batch_op.drop_index(batch_op.f('idx_activity_is_active'))

    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_activity_activity_id'))
        batch_op.drop_index(batch_op.f('idx_user_activity_user_activity'))
        batch_op.drop_index(batch_op.f('idx_user_activity_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_activity_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_activity_user_activity'), ['user_id', 'activity_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_activity_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_activity_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_city_id'), ['city_id'], unique=False)

    # ### end Alembic commands ###
