"""empty message

Revision ID: c441f0344b32
Revises: 
Create Date: 2025-11-29 11:21:55.724919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c441f0344b32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('community_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('community_admins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('community_admins_community_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('community_admins_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])

    with op.batch_alter_table('community_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('community_members_community_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('community_members_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])

    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('email_verifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_created_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('event_community_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_participants_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('event_participants_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('post_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('post_like_post_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_like_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('preferences',
               existing_type=sqlite.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_like_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('post_like_post_id_fkey'), 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_participants_event_id_fkey'), 'event', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('event_participants_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_community_id_fkey'), 'community', ['community_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('event_created_by_fkey'), 'user', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('email_verifications_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('community_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('community_members_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('community_members_community_id_fkey'), 'community', ['community_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('community_admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('community_admins_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('community_admins_community_id_fkey'), 'community', ['community_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('community_created_by_fkey'), 'user', ['created_by'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
