"""empty message

Revision ID: f879646f238a
Revises: 6beb6c0538ca
Create Date: 2025-10-13 15:43:13.519211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f879646f238a'
down_revision = '6beb6c0538ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
